Qodana action fix 7

diff --git a/qodana.yaml b/qodana.yaml
--- a/qodana.yaml
+++ b/qodana.yaml
@@ -26,25 +26,35 @@ profile:
 projectJDK: "21" #(Applied in CI/CD pipeline)
 
 #Execute shell command before Qodana execution (Applied in CI/CD pipeline)
-#bootstrap:
+bootstrap: |+
+  if [ ! -f "build/compile_commands.json" ] && [ -f "CMakeLists.txt" ]; then
+    cmake -S . -B build \
+    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
+    -DCMAKE_BUILD_TYPE=Debug \
+    -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake 2>/dev/null || true
+  fi
 
-#Install IDE plugins before Qodana execution (Applied in CI/CD pipeline)
-#plugins:
-#  - id: <plugin.id> #(plugin id can be found at https://plugins.jetbrains.com)
+exclude:
+  - paths:
+      - cmake-build-debug/**
+    name: build files
 
-# Quality gate. Will fail the CI/CD pipeline if any condition is not met
-# severityThresholds - configures maximum thresholds for different problem severities
-# testCoverageThresholds - configures minimum code coverage on a whole project and newly added code
-# Code Coverage is available in Ultimate and Ultimate Plus plans
-#failureConditions:
-#  severityThresholds:
-#    any: 15
-#    critical: 5
-#  testCoverageThresholds:
-#    fresh: 70
-#    total: 50
-  
+  #Install IDE plugins before Qodana execution (Applied in CI/CD pipeline)
+  #plugins:
+  #  - id: <plugin.id> #(plugin id can be found at https://plugins.jetbrains.com)
+
+  # Quality gate. Will fail the CI/CD pipeline if any condition is not met
+  # severityThresholds - configures maximum thresholds for different problem severities
+  # testCoverageThresholds - configures minimum code coverage on a whole project and newly added code
+  # Code Coverage is available in Ultimate and Ultimate Plus plans
+  #failureConditions:
+  #  severityThresholds:
+  #    any: 15
+  #    critical: 5
+  #  testCoverageThresholds:
+  #    fresh: 70
+  #    total: 50
+
 #Qodana supports other languages, for example, Python, JavaScript, TypeScript, Go, C#, PHP
 #For all supported languages see https://www.jetbrains.com/help/qodana/linters.html
 linter: jetbrains/qodana-cpp:2025.3-eap
-withinDocker: 'false'
